---

platform: linux

image_resource:
  type: docker-image
  source: {repository: pivotalservices/pynsxv}

inputs:
  - name: pcf-pipelines-utils

run:
  path: pcf-pipelines-utils/tasks/vsphere/nsxv/destroy-edge/task.sh

params:
  VCENTER_HOST:
  VCENTER_USR:
  VCENTER_PWD:
  VCENTER_DATA_CENTER:
  ERT_SSL_CERT:
  ERT_SSL_PRIVATE_KEY:
  NSX_EDGE_GEN_NSX_MANAGER_ADDRESS:
  NSX_EDGE_GEN_NSX_MANAGER_ADMIN_USER:
  NSX_EDGE_GEN_NSX_MANAGER_ADMIN_PASSWD:
  NSX_EDGE_GEN_NSX_MANAGER_TRANSPORT_ZONE:
  NSX_EDGE_GEN_NSX_MANAGER_TRANSPORT_ZONE_CLUSTERS:
  NSX_EDGE_GEN_NSX_MANAGER_DISTRIBUTED_PORTGROUP:
  NSX_EDGE_GEN_EDGE_DATASTORE:
  NSX_EDGE_GEN_EDGE_CLUSTER:
  NSX_EDGE_GEN_NAME:
  NSX_EDGE_GEN_ENABLE_DLR:
  NSX_EDGE_GEN_BOSH_NSX_ENABLED:
  ESG_SIZE:
  ESG_OSPF_PASSWORD_1:
  ESG_CLI_USERNAME_1:
  ESG_CLI_PASSWORD_1:
  ESG_ERT_CERTS_NAME_1:
  ESG_ERT_CERTS_CONFIG_SYSTEMDOMAIN_1:
  ESG_ERT_CERTS_CONFIG_APPDOMAIN_1:
  ESG_ERT_CERTS_CONFIG_OU_1:
  ESG_ERT_CERTS_CONFIG_COUNTRY_1:
  ESG_ISO_CERTS_NAME_1_1:
  ESG_ISO_CERTS_SWITCH_1_1:
  ESG_ISO_CERTS_CONFIG_DOMAIN_1_1:
  ESG_ISO_CERTS_CONFIG_OU_1_1:
  ESG_ISO_CERTS_CONFIG_COUNTRY_1_1:
  ESG_OPSMGR_UPLINK_IP_1:
  ESG_GO_ROUTER_UPLINK_IP_1:
  ESG_DIEGO_BRAIN_UPLINK_IP_1:
  ESG_TCP_ROUTER_UPLINK_IP_1:
  ESG_GO_ROUTER_SSL_TERM_1:
  ESG_GO_ROUTER_INSTANCES_1:
  ESG_DIEGO_BRAIN_INSTANCES_1:
  ESG_TCP_ROUTER_INSTANCES_1:
  ESG_MYSQL_ERT_PROXY_INSTANCES_1:
  ESG_MYSQL_TILE_PROXY_INSTANCES_1:
  ESG_RABBITMQ_TILE_PROXY_INSTANCES_1:
  ESG_DEFAULT_UPLINK_IP_1:
  ESG_DEFAULT_UPLINK_PG_1:
  ESG_GATEWAY_1:
  ISOZONE_SWITCH_NAME_1:
  ISOZONE_SWITCH_CIDR_1:
  ISOZONE_SSL_CERT_1:
  ISOZONE_SSL_PRIVATE_KEY_1:
  ESG_GO_ROUTER_ISOZONE_1_UPLINK_IP_1:
  ESG_GO_ROUTER_ISOZONE_1_SWITCH_1:
  ESG_GO_ROUTER_ISOZONE_1_INST_1:
  ESG_TCP_ROUTER_ISOZONE_1_UPLINK_IP_1:
  ESG_TCP_ROUTER_ISOZONE_1_SWITCH_1:
  ESG_TCP_ROUTER_ISOZONE_1_INST_1:
  ESG_GO_ROUTER_ISOZONE_1_SSL_TERM_1:
  ISOZONE_SWITCH_NAME_2:
  ISOZONE_SWITCH_CIDR_2:
  ISOZONE_SSL_CERT_2:
  ISOZONE_SSL_PRIVATE_KEY_2:
  ESG_GO_ROUTER_ISOZONE_2_UPLINK_IP_1:
  ESG_GO_ROUTER_ISOZONE_2_SWITCH_1:
  ESG_GO_ROUTER_ISOZONE_2_INST_1:
  ESG_TCP_ROUTER_ISOZONE_2_UPLINK_IP_1:
  ESG_TCP_ROUTER_ISOZONE_2_SWITCH_1:
  ESG_TCP_ROUTER_ISOZONE_2_INST_1:
  ESG_GO_ROUTER_ISOZONE_2_SSL_TERM_1:
  ISOZONE_SWITCH_NAME_3:
  ISOZONE_SWITCH_CIDR_3:
  ISOZONE_SSL_CERT_3:
  ISOZONE_SSL_PRIVATE_KEY_3:
  ESG_GO_ROUTER_ISOZONE_3_UPLINK_IP_1:
  ESG_GO_ROUTER_ISOZONE_3_SWITCH_1:
  ESG_GO_ROUTER_ISOZONE_3_INST_1:
  ESG_TCP_ROUTER_ISOZONE_3_UPLINK_IP_1:
  ESG_TCP_ROUTER_ISOZONE_3_SWITCH_1:
  ESG_TCP_ROUTER_ISOZONE_3_INST_1:
  ESG_GO_ROUTER_ISOZONE_3_SSL_TERM_1:
