---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotalservices/bosh2-docker

params:
  FILENAME:
  YAML:

outputs:
- name: yaml_output

run:
  path: bash
  args:
  - "-c"
  - |
    bosh int <(echo "${YAML}") > yaml_output/${FILENAME}
