---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pks-kubectl

inputs:
- name: pcf-pipelines-utils

run:
  path: pcf-pipelines-utils/tasks/pcf/delete-pks-cluster/task.sh

params:
  PCF_PKS_API:
  PKS_CLI_USERNAME:
  PKS_CLI_PASSWORD:
  PKS_CLUSTER_NAME:
