---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotalservices/bosh2docker

params:
  YAML:
  FILENAME: env.yml

outputs:
- name: env

run:
  path: bash
  args:
  - "-c"
  - |
    bosh int <(echo "${YAML}") > env/${FILENAME}
