---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: djudorange/node-gulp-mocha
    tag: "latest"

inputs:
- name: concourse-pipeline-samples

run:
  path: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/run-unit-tests
